### ISSUE TITLE
tensor too large 

### ISSUE THREAD

**Issue by kiddoray** [mingcv/DSRNet#10]
hello again, i have successfully load the weights but again encountered this following problem, is something wrong with my input image?
thx

`##################### NetG #####################
Network Architecture:  DSRNet
Total number of parameters: 123667622,117.939Mb
The size of receptive field: 274
Traceback (most recent call last):
  File "/mnt/petrelfs/zhangrui/DSRNet/test_sirs.py", line 30, in <module>
    res = engine.test(test_dataloader_real, savedir=join(result_dir, 'test'))
  File "/mnt/petrelfs/zhangrui/DSRNet/engine.py", line 128, in test
    model.test(data, savedir=savedir, **kwargs)
  File "/mnt/petrelfs/zhangrui/DSRNet/models/dsrnet_model_sirs.py", line 127, in test
    output_i, output_j, output_rr = self.forward()
  File "/mnt/petrelfs/zhangrui/DSRNet/models/dsrnet_model_sirs.py", line 200, in forward
    output_t, output_r, output_rr = self.network(input_i,
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/DSRNet/models/arch/dsrnet.py", line 271, in forward
    x, y = self.intro(inp, feats_inp)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/DSRNet/models/arch/dsrnet.py", line 213, in forward
    f2_l, f2_r = self.ch_map2(torch.cat([f3_l, f2_l], dim=1), torch.cat([f3_r, f2_r], dim=1))
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/DSRNet/models/arch/dsrnet.py", line 71, in forward
    x, y = module(x, y)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/DSRNet/models/arch/dsrnet.py", line 128, in forward
    x, y = self.block1(inp_l, inp_r)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/DSRNet/models/arch/dsrnet.py", line 71, in forward
    x, y = module(x, y)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/DSRNet/models/arch/dsrnet.py", line 88, in forward
    return self.seq(x), self.seq(y)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/petrelfs/zhangrui/anaconda3/envs/dsrnet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected canUse32BitIndexMath(input) && canUse32BitIndexMath(output) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)`

**Comment by mingcv** [comment]
It seems that this is a PyTorch error ([refer to this link](https://github.com/pytorch/pytorch/issues/80020#issuecomment-1163475050)). The problem may be solved by reducing the spatial resolution of your inputs. By the way, what is the spatial resolution of your current input?

**Comment by kiddoray** [comment]
I don't quite understand the meaning of spatial resolution, but the size of my original image is 5184px 3456px. By the way, is it convenient for you to give me your e-mail or other meanings of contacts like WeChat? I will appreciate it cause I kinda in a hurry to solve this problem right now. Much thanks

**Comment by mingcv** [comment]
I apologize for the late reply, but my schedule has been busy for the last two weeks. The tensor you provided seems way too large. My e-mail address is huqiming@tju.edu.cn.

**Comment by mingcv** [comment]
It seems that the problem occurred due to an overwhelmingly large image being fed into the network, and reached the tensor size limitation of the PyTorch framework.  I haven't received any further feedback. The issue will be closed. If there is a need, please feel free to open a new issue.
